spring:
  application:
    name: web-gateway
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        health-check-path: /actuator/health
        enabled: true
server:
  port: 8080