spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3308/jobscape
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        health-check-path: /actuator/health
        enabled: true
server:
  port: 8081